name: Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    
    steps:
      - name: Welcome new issue creator
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.sender.login;
            const issue_number = context.issue.number;
            
            // Check if this is the user's first issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: creator,
              state: 'all'
            });
            
            if (issues.data.length === 1) {
              await github.rest.issues.createComment({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `👋 Welcome @${creator}! Thank you for opening your first issue.\n\nA maintainer will review this shortly. In the meantime, check out our [Contributing Guide](https://github.com/Olanetsoft/compact-by-example/blob/main/CONTRIBUTING.md) and join us on [Discord](https://discord.com/invite/midnightnetwork)!`
              });
            }
      
      - name: Welcome new contributor
        if: github.event_name == 'pull_request_target'
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.sender.login;
            const pr_number = context.issue.number;
            
            // Check if this is the user's first PR
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all'
            });
            
            const userPRs = prs.data.filter(pr => pr.user.login === creator);
            
            if (userPRs.length === 1) {
              await github.rest.issues.createComment({
                issue_number: pr_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `🎉 Congratulations on your first Pull Request, @${creator}!\n\nThank you for contributing to Compact by Example! A maintainer will review your PR soon.\n\n**While you wait:**\n- Make sure all CI checks pass ✅\n- Review our [Code of Conduct](https://github.com/Olanetsoft/compact-by-example/blob/main/CODE_OF_CONDUCT.md)\n- Join our community on [Discord](https://discord.com/invite/midnightnetwork)\n\nWe appreciate your contribution! 🙌`
              });
            }
